// Code generated by mockery v2.24.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FriendMsgSender is an autogenerated mock type for the FriendMsgSender type
type FriendMsgSender struct {
	mock.Mock
}

// SendMsgFriendAdded provides a mock function with given fields: userID, friendID
func (_m *FriendMsgSender) SendMsgFriendAdded(userID int64, friendID int64) {
	_m.Called(userID, friendID)
}

// SendMsgFriendRemoved provides a mock function with given fields: userID, friendID
func (_m *FriendMsgSender) SendMsgFriendRemoved(userID int64, friendID int64) {
	_m.Called(userID, friendID)
}

type mockConstructorTestingTNewFriendMsgSender interface {
	mock.TestingT
	Cleanup(func())
}

// NewFriendMsgSender creates a new instance of FriendMsgSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFriendMsgSender(t mockConstructorTestingTNewFriendMsgSender) *FriendMsgSender {
	mock := &FriendMsgSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
